---
version: '3.3'
services:
  mongo_db:
    image: mongo:${MONGO_VER}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - ${POST_DATABASE_HOST}
          - ${COMMENT_DATABASE_HOST}
  ui:
    build: ./ui
    image: ${USERNAME}/ui:${UI_VER}
    environment:
      - POST_SERVICE_HOST
      - POST_SERVICE_PORT
      - COMMENT_SERVICE_HOST
      - COMMENT_SERVICE_PORT
    ports:
      - ${UI_PORT}:9292/tcp
    networks:
      front_net:
  post:
    build: ./post-py
    image: ${USERNAME}/post:${POST_VER}
    environment:
      - POST_DATABASE_HOST
      - POST_DATABASE
    networks:
      front_net:
        aliases:
          - ${POST_SERVICE_HOST}
      back_net:
  comment:
    build: ./comment
    image: ${USERNAME}/comment:${COMMENT_VER}
    environment:
      - COMMENT_DATABASE_HOST
      - COMMENT_DATABASE
    networks:
      front_net:
        aliases:
          - ${COMMENT_SERVICE_HOST}
      back_net:

volumes:
  post_db:

networks:
  front_net:
    ipam:
      config:
        - subnet: ${FRONT_SUBNET}
  back_net:
    ipam:
      config:
        - subnet: ${BACK_SUBNET}
...
