global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
  - name: 'slack-notifications'
    slack_configs:
    - channel: '@eugenenuke'
